### ISSUE TITLE
A Wii U GamePad update is required.

### ISSUE THREAD

**Issue by nastys** [rolandoislas/drc-sim#10]
![screenshot from 2017-03-05 12-35-04](https://cloud.githubusercontent.com/assets/7950891/23586921/6e3fcb38-01a0-11e7-8fdd-fbb3d8e2269b.png)
![screenshot from 2017-03-05 12-39-00](https://cloud.githubusercontent.com/assets/7950891/23586929/d15a1a5c-01a0-11e7-8725-98d1bc02215b.png)

The update will always fail to install. It is hard to bypass this message.
Maybe the region is hardcoded?

**Comment by rolandoislas** [comment]
What version/branch is this and what is the region of the Wii U?

**Comment by nastys** [comment]
I was using the master branch but I've noticed that the development branch is able to bypass that, somehow.
![screenshot from 2017-03-05 16-02-39](https://cloud.githubusercontent.com/assets/7950891/23588403/77356582-01bd-11e7-8874-6338ab173293.png)
After clicking OK I can use the console normally. I don't know if it is intended to do that but it works.
By the way, Wii U is European.

**Comment by rolandoislas** [comment]
The Wii U sends a command with the [service id 5](http://libdrc.org/docs/re/sc-cmd.html#service-id-5) and method 0x06. The response it expects is the firmware version. 

From the libdrc documentation:
> Returns the 4 byte UIC firmware version followed by the first 768 bytes of the UIC EEPROM.

At the moment the dev branch sends null data and the master/version 1.1 send an old European version. With the correct, dumped version data the gamepad would register as updated to the Wii U.
