### ISSUE TITLE
Gamepad Version Data

### ISSUE THREAD

**Issue by rolandoislas** [rolandoislas/drc-sim#16]
Currently drc-sim sends null data to the Wii U when asked for the firmware version.

Make that not so.

**Comment by Flumper** [comment]
I know im being a pain in the ass here, but I think this might relate to my new problem. I stupidly done a system reset to get rid of parental controls and any Mii's that were on the system (which I now know was a very stupid move) as now im getting a memory error and no touchpad control when the gamepad pairs back up at system restart. Im sorry for all the problems im having, im usually good with consoles but this one has jinxed me from the start lol.

**Comment by rolandoislas** [comment]
Where does the error appear? It sounds like it is from the Wii U (on screen). Is the error similar to #10?

**Comment by Flumper** [comment]
Sorry for taking so long to reply. Anyway this is what happens.

Step 1 - Turn on the console
![img_20170329_214424](https://cloud.githubusercontent.com/assets/26669088/24476318/be576c74-14ca-11e7-809e-438b25afe881.jpg)

Step 2 - Press the sync button on the console
![img_20170329_214504](https://cloud.githubusercontent.com/assets/26669088/24476344/e14e08d2-14ca-11e7-9150-dc518bfd1f8d.jpg)

Step 3 - Get the key and start the server and it pairs ok
![img_20170329_214852](https://cloud.githubusercontent.com/assets/26669088/24476415/13c0d524-14cb-11e7-85bd-9b76a453a728.jpg)

Step 4 - Run the client and get this screen on the tv
![img_20170329_214858](https://cloud.githubusercontent.com/assets/26669088/24476489/4e465c1e-14cb-11e7-9960-bc185eead693.jpg)
and this on the client
![img_20170329_215147](https://cloud.githubusercontent.com/assets/26669088/24476502/64c9186e-14cb-11e7-83c6-50754fceb95f.jpg)

Step 5 - About 5 seconds later on the client screen
![img_20170329_215238](https://cloud.githubusercontent.com/assets/26669088/24476527/7fd53278-14cb-11e7-909c-6fd08d57b3e4.jpg)

Then the console freezes and I have to power off.

**Comment by rolandoislas** [comment]
Version 1.1 sends the old firmware data, but the Wii U may attempt to update it and fail anyway.

If the newer server is started with the `-f` parameter (e.g. `drc-sim-backend -f`) the logging will increase in verbosity. With the `~/.drc-sim/log/backend.log` I might be able to get a better understanding of what the Wii U is requesting. Note that the log from the terminal (all output) and `~/.drc-sim/log/wpa.log` will contain SSID found when connecting and is not required.

**Comment by Flumper** [comment]
Sorry m8, didnt see the last comment before I got a loan of a pad and used that to start and update. 

Thankx for all you did to make this possible even without the sound, sorry if I was a pain in the ass lol.

**Comment by sewerat** [comment]
Hi, I'm having the same problem too. This may be a problem because I am running the server and the client on the same slow computer. Basically what happens is I turn on the wiiU and connect the virtual gamepad but when I tap the screen, the client and WiiU freeze up and after about 5 seconds, it displays the message "A System Memory Error Has Occurred." I don't know if this was because of the know if this is because of the server or the client. It would be great if you could find a patch for this or identify the issue. Thanks so much!

**Comment by rolandoislas** [comment]
If it only happens after touch input, try to navigate with button input. Also see [this](#issuecomment-290273028) previous comment for enabling debug logging.

**Comment by sewerat** [comment]
Sorry to bother you again but it actually requires you to touch the screen and I don't think theres button input for that. Do you know another way?

**Comment by rolandoislas** [comment]
I need the logs to know more about the error.

**Comment by sewerat** [comment]
Here are the outputs of the client and the server
[Output logs.txt](https://github.com/rolandoislas/drc-sim/files/888349/Output.logs.txt)

**Comment by rolandoislas** [comment]
The Wii U now registers DRC Sim as an [up to date](https://cloud.githubusercontent.com/assets/6559115/24689692/18e8d23e-197d-11e7-82bd-bb4d6a66bfca.png) gamepad.

The data is from an NA gamepad, so I expect it will not work in other regions.

**Comment by rolandoislas** [comment]
The dev branch now has a region selector in the GUI. Could someone test the NA version data with a Wii U of a different region?

**Comment by itshistorym** [comment]
Swedish wii u. Tried the NA version data and it worked better until it crashed with the same system memory error in the system setup right after the screen resolution settings. 

[tttt.txt](https://github.com/rolandoislas/drc-sim/files/900425/tttt.txt)

**Comment by itshistorym** [comment]
Now it worked although now it wants to update the gamepad and gets the error:
Error Code 165-9901
The update cannot be completed using a Wii u GamePad designed for different region.

**Comment by rolandoislas** [comment]
Did the setup complete? The error code is the same as in #10.

After the setup, reconnect with no specified region or "None". The Wii U will display a few messages about it being unable to communicate with the gamepad but it should still work.

**Comment by itshistorym** [comment]
The setup did complete. And now it 100% works after I changed the region to none like you sad. Thanks man, really appreciate your work and your quick answers.
