### ISSUE TITLE
Could not authenticate. Check the entered PIN

### ISSUE THREAD

**Issue by rapterda23** [rolandoislas/drc-sim#17]
Im receiving this error when trying to pair and yes I have doubled checked the symbols and its still receiving this error. If you could please help me I would really appreciate it. 

Thanks,
Daniel

**Comment by rolandoislas** [comment]
I will need the [wpa.log](https://github.com/rolandoislas/drc-sim/wiki/Logging) to see error details.

**Comment by rolandoislas** [comment]
I remember experiencing a similar issue when network-manager was still using the device. Try `sudo service network-manager restart`.

**Comment by rapterda23** [comment]
Hey rolandoslas I've tried that already, I restarted that manager a couple times and still same issue. My wifi card is transmitting on a 5.2frequency so that should be okay. Ive tried just about everything and I can't seem to find that log file.

**Comment by rapterda23** [comment]
This is the screen I'm supposed to be on correct?
![photo on 4-3-17 at 11 57 am](https://cloud.githubusercontent.com/assets/16924565/24625721/bf892414-1864-11e7-8c9b-6f576479f853.jpg)

**Comment by rolandoislas** [comment]
Try `sudo cat /root/.drc-sim/log/wpa.log` or `cat ~/.drc-sim/log/wpa.log`

**Comment by nhardman3x** [comment]
can you help me im in the same boat.

 sudo cat /root/.drc-sim/log/wpa_supplicant_drc.log
[sudo] password for nick: 
Successfully initialized wpa_supplicant
wlxc8d719c44c21: Trying to associate with 34:af:2c:52:51:76 (SSID='WiiU34af2c5251734af2c525176_STA1' freq=5805 MHz)
wlxc8d719c44c21: CTRL-EVENT-ASSOC-REJECT status_code=1
wlxc8d719c44c21: Trying to associate with 34:af:2c:52:51:76 (SSID='WiiU34af2c5251734af2c525176_STA1' freq=5805 MHz)
wlxc8d719c44c21: CTRL-EVENT-ASSOC-REJECT status_code=1
wlxc8d719c44c21: Trying to associate with 34:af:2c:52:51:76 (SSID='WiiU34af2c5251734af2c525176_STA1' freq=5805 MHz)
wlxc8d719c44c21: CTRL-EVENT-ASSOC-REJECT status_code=1
wlxc8d719c44c21: Trying to associate with 34:af:2c:52:51:76 (SSID='WiiU34af2c5251734af2c525176_STA1' freq=5805 MHz)
wlxc8d719c44c21: CTRL-EVENT-ASSOC-REJECT status_code=1
wlxc8d719c44c21: Trying to associate with 34:af:2c:52:51:76 (SSID='WiiU34af2c5251734af2c525176_STA1' freq=5805 MHz)
wlxc8d719c44c21: CTRL-EVENT-ASSOC-REJECT status_code=1
CTRL_IFACE: Detach monitor that cannot receive messages: /tmp/wpa_ctrl_6012-2\x00
nl80211: deinit ifname=wlxc8d719c44c21 disabled_11b_rates=0
wlxc8d719c44c21: CTRL-EVENT-TERMINATING 

please help me

**Comment by opencma** [comment]
@nhardman3x the best approach is to try one of the wireless interfaces on the wiki known to work: https://github.com/rolandoislas/drc-sim/wiki/Wireless-Interface.
