### ISSUE TITLE
No Wii U compatible wireless interfaces found

### ISSUE THREAD

**Issue by gleparc** [rolandoislas/drc-sim#2]
I got everything installed and working - when I run the drc-sim-helper and choose the get_key option, I see "No Wii U compatible wireless interfaces found". This makes sense because my current wifi adaptor (a usb stick) offers only 2.4 Ghz as i can see here:

sudo iwlist wlan0 channel

wlan0     14 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          ....snipped for brevity...
          Channel 14 : 2.484 GHz

So it is simply a matter of me buying a 5ghz 802.11n capable wifi adapter and installing it, then checking it for 5 Ghz frequency? Is this sufficient for it to be considered a Wii U compatible wifi interface? Are there any other requirements (technical specs) needed?  I just want to make sure before I run out and buy one. 

I would recommend adding the "sudo iwlist wlan0 channel" command to the wiki for users to check their wifi capabilities beforehand. 

thanks a lot for releasing this code!

**Comment by rolandoislas** [comment]
Any 5Ghz, 802.11n compatible wireless interface should be compatible as long as it has the appropriate drivers and would be capable of connecting to such a network under normal circumstances.

I use an AE1000 network adapter and someone else has had success with a WNDA3100v3.

**Comment by jleacox** [comment]
I've connected an android as a 5ghz device and have the server installed (seemingly successfully) using the dev version. Ubuntu seems to work fine using the 5g interface from my phone to connect to the internet, and even registers it under the normal interface list. But the server doesn't see anything under the Wii U interface list dropdown. Is this just my network devices not detecting the wii u?

**Comment by ByronJosueBC** [comment]
Hey @jleacox were you able to get it to work?
