### ISSUE TITLE
How to go back to older an build?

### ISSUE THREAD

**Issue by colecarn** [rolandoislas/drc-sim#24]
About 10 days ago, I installed DRC Sim on a virtual machine running Ubuntu. It was working flawlessly.

Just recently, I created a new VM, and reinstalled DRC Sim using the easy install script, as I did before.

I'm now having connectivity issues. Currently, I can pair with my WiiU, however, the desktop client briefly connects, then disconnects. I'm not sure if the issue is on my end, or a problem with the latest 1.5 release.

I want to go back to an older build, though not sure exactly how. I've downloaded the archived tar (1.4 and 1.5 beta), extracted them, then ran ./install.sh, which seems to always clone and install the latest build.

I'm a bit confused on the usage of the branch/option, and how to apply to the install command. If I try **sudo ./install.sh local** I get "Invalid branch "local"".

Can you please list a command example to correctly install an older build.

Thank you, and thanks for the work on this fantastic application.

**Comment by rolandoislas** [comment]
Anything pre 1.5 will require a [manual install](https://github.com/rolandoislas/drc-sim/wiki/Install---Debian), as previous versions of the install script did not have a local option.

[This script](https://gist.github.com/rolandoislas/e60cfe4f2c5ff90100c65d243797f02d) should work. Replace the current and give it the `local` option.

`sudo bash ./install.sh local`

**Comment by colecarn** [comment]
Thanks for the response.

I have 1.4 downloaded and extracted. When I go into the folder, I open command prompt there than run

` sudo bash ./install.sh local`

and I get the following...

```
  https://github.com/rolandoislas/drc-sim
Command apt-get found.
Invalid branch "local"
Usage: <install.sh> [argument]
  Defaults to install.
  Arguments:
    -h, help : help menu
    branch : branch to use for drc-sim (master or develop) master is used by default
    uninstall : uninstall DRC Sim
```

**Comment by rolandoislas** [comment]
The linked script needs to be downloaded to the same directory as the
bundled script.
-- 
Rolando Islas
admin@rolandoislas.com
https://www.rolandoislas.com

**Comment by colecarn** [comment]
> The linked script needs to be downloaded to the same directory as the bundled script.

That did it. Must of missed that step. I'm back on 1.4, and have successfully connected to my Wii U. Thanks again for your support and brilliant work!

Would it be beneficial for the build version number to appear on the Sim Server GUI for easy reference?
