### ISSUE TITLE
pkg-config Not Installed On Deb 8.8.0

### ISSUE THREAD

**Issue by gudenau** [rolandoislas/drc-sim#31]
The script does not install pkg-config on Debian 8.8.0 which is required to make wpa_supplicant.

**Comment by rolandoislas** [comment]
The master branch should resolve pkg-config via python3-dev. The develop branch adds it as a direct dependency. Was there an issue with the install? If so, what version and/or commit was the script from?

**Comment by gudenau** [comment]
I was using what should have been the latest script on master, `curl url | sudo bash -s master` or whatever it was. It seemed to install python-dev without errors, but it didn't install pkg-config by itself. Installing it with apt-get fixed this issue.

**Comment by opencma** [comment]
Fixed in version 2.0.
