### ISSUE TITLE
"Get Key" dropdown window is empty

### ISSUE THREAD

**Issue by Pucciogaeshi** [rolandoislas/drc-sim#36]
Hey there, I'm a total noob on this sort of things so I really don't know what I might be doing wrong. I installed Drc Sim on a Virtual Machine running Linux using the normal install method, and upon opening the program I am greeted by 4 tabs, Run Server, Get Key, Log and About. I am following Cheddar's youtube tutorial, but when he clicks on the dropdown window in Get Key he has an option while I have zero. Why might that be?

**Comment by bbobffrench** [comment]
I'm pretty sure virtual machines don't have Bluetooth by default. When I installed it I needed to dual boot Ubuntu on my computer but you might be able to get Bluetooth on a virtual machine. Also it might be a completely different problem but maybe try it again with Bluetooth.

**Comment by opencma** [comment]
The USB wireless interface will need to be attached to the VM. This varies by the viewer, but it should be accessible at the bottom status bar on VMWare Player and Virtualbox or through their menus.

**Comment by Pucciogaeshi** [comment]
Ah, is the USB wireless interface necessary? The requirements mentioned a wireless networking interface but I didn't think it had to be a USB one.  Totally in over my head on all this, sorry ahah

**Comment by opencma** [comment]
I have not tested bridging a wireless card, but I do not think it will work. It shouldn't hurt to test it in any case.
