### ISSUE TITLE
get key drop down menu is empty

### ISSUE THREAD

**Issue by IHateBlue** [rolandoislas/drc-sim#38]
So I got to the "get key" part but when I open the drop down tab I see nothing. Apparently I have to click on something called "wlp3s0" but I don't see it in the tab.

im using virtual box btw. please help as fast as possible!

**Comment by opencma** [comment]
See #36 and the [wireless interface](https://github.com/rolandoislas/drc-sim/wiki/Wireless-Interface) page.

**Comment by IHateBlue** [comment]
alright

**Comment by IHateBlue** [comment]
whats a USB wireless interface?

**Comment by opencma** [comment]
> whats a USB wireless interface?

A wireless USB adapter is required to run DRC Sim Server. I am unaware of any onboard card that has worked.

> alright i figured out what i need to do, but is there a way i can virtually use a wireless interface?

If virtual means avoid hardware altogether, no. Attaching a USB device, on the other hand, has different steps depending on virtualization software and host.
