### ISSUE TITLE
can i use bridging to host my server?

### ISSUE THREAD

**Issue by IHateBlue** [rolandoislas/drc-sim#40]
ive tried everything possible in the "get key drop down tray" issue but i cant figure it out, i dont have a dongle thing but i do have ethernet, so how do i use it for the drop down?

**Comment by opencma** [comment]
It is not possible. Please read the [wiki](https://github.com/rolandoislas/drc-sim/wiki).

Edit: To clarify, it is not possible to use DRC Sim with ethernet alone. A compatible wireless adapter is required.
