### ISSUE TITLE
Without 5ghz router?

### ISSUE THREAD

**Issue by Kevoss2** [rolandoislas/drc-sim#43]
Is there a way for me to use this if my laptop supports 5ghz (Intel Centrino Ultimate-N 6300 AGN) but not my router (d-link DIR-605L) ?  When I try to find the key, there are no options in the drop down menu for the network adapter (Ubuntu, VM).

**Comment by opencma** [comment]
An onboard wireless interface will not work within a VM for DRC Sim. Not many adapters outside of the [rt2800 chipset](https://github.com/rolandoislas/drc-sim/wiki/Wireless-Interface#compatible-usb-devices) work with it in general. I do not recall reports of success with a device of another chipset. The connection is between the Wii U and the wireless interface directly; the router will not be used.

**Comment by Kevoss2** [comment]
Would the onboard wireless interface work if Ubuntu is the main OS (not in VM)?

**Comment by opencma** [comment]
It could, but the odds are high that it would not.
