### ISSUE TITLE
CTRL-EVENT-ASSOC-REJECT when trying to associate to Wii U (T4U Archer A1300 - RTL8812AU)

### ISSUE THREAD

**Issue by sh4444dow** [rolandoislas/drc-sim#46]
Hello @rolandoislas, first of all, thanks for your investment into drc simulation fo Wii U.

I've purchased a T4U Archer A1300 (http://amzn.to/2fHcdZ5) which is normally compatible with RTL8812AU driver. The first problem is that **only** [abperiasamy/rtl8812AU_8821AU_linux](https://github.com/abperiasamy/rtl8812AU_8821AU_linux/) driver let my WiFI dongle be recognized... Your version [rolandoislas/rtl8812AU](https://github.com/rolandoislas/rtl8812AU) unfortunately does not work. I first thought that was missing the USB ID `2357:010D` into [os_dep/linux/usb_intf.c](https://github.com/rolandoislas/rtl8812AU/blob/driver-4.3.14/os_dep/linux/usb_intf.c), but unfortunately this was not sufficient to get my dongle be recognized.

Well, being well detected, I can launch DRC Sim Server, go into _Get Key_, start scan, but when shows _Connecting_, an error `wlan1: CTRL-EVENT-ASSOC-REJECT status_code=1` is thrown. 

May you help me to solve my problem ?

Thanks in advance, Sincerely, @sh4444dow

Configuration : Debian GNU/Linux 8.9 (jessie) - kernel 3.16.0-4-amd64

**Comment by opencma** [comment]
I unfortunatly never got the rtl8812AU driver to work fully. The furthest was associating with the Wii U, but when requesting an IP via DHCP, a response was never returned.

Is the device visible in `ifconfig -a` or `iw list` output? The GUI ignores anything that does not display as a 5GHz device from the iw output. If it is working correctly, running DRC Sim Server via the CLI will allow any interface name to be passed. Documentation is avaliable [here](https://github.com/rolandoislas/drc-sim/wiki/Connecting#running--cli).

**Comment by sh4444dow** [comment]
The Wi-Fi dongle was fully recognized by drc-sim-server as indicated in my first message, Indeed I launch pairing from GUI. 
Nevertheless, I sold my WiFi dongle because the drivers for this dongle seems to be completely broken and not fully functionnal (with WPS features ??), and none did work with drc-sim-server.
I close this ticket.
