### ISSUE TITLE
Installation fails on Linux Mint 18.3

### ISSUE THREAD

**Issue by ghost** [rolandoislas/drc-sim#49]
I used the easy install script for Debian systems, and the script runs normally until it checks for netlink support, at which point it tries to find a Python file and fails (from what I can tell in the log). I already have Python and all the dependencies installed.

Here is the log since I have little idea about what's going on:

vanevander@blapi ~ $ curl -s https://raw.githubusercontent.com/rolandoislas/drc-sim/master/install.sh | sudo bash -s master
[sudo] password for vanevander: 
Drc-sim installer (script version 1.1.3)
	https://github.com/rolandoislas/drc-sim
Command apt-get found.
Installing dependencies.
python3 [INSTALLED]
python3-pip [INSTALLED]
net-tools [INSTALLED]
wireless-tools [INSTALLED]
sysvinit-utils [INSTALLED]
psmisc [INSTALLED]
rfkill [INSTALLED]
isc-dhcp-client [INSTALLED]
ifmetric [INSTALLED]
python3-tk [INSTALLED]
gksu [INSTALLED]
git [INSTALLED]
libssl-dev [INSTALLED]
libnl-genl-3-dev [INSTALLED]
gcc [INSTALLED]
make [INSTALLED]
pkg-config [INSTALLED]
libavcodec-dev [INSTALLED]
libswscale-dev [INSTALLED]
libjpeg-dev [INSTALLED]
cmake [INSTALLED]
Found existing git directory /opt/drc_sim/wpa
Cloning https://github.com/rolandoislas/drc-hostap.git into /opt/drc_sim/wpa
Cloned https://github.com/rolandoislas/drc-hostap.git
Compiling wpa_supplicant_drc
Compile log at /opt/drc_sim/wpa/wpa_supplicant/make.log
Installing wpa_supplicant_drc and wpa_cli_drc to /usr/local/bin
Compiled wpa_supplicant
Found existing git directory /opt/drc_sim/drc_sim_c
Cloning https://github.com/rolandoislas/drc-sim-c.git into /opt/drc_sim/drc_sim_c
Cloned https://github.com/rolandoislas/drc-sim-c.git
Compiling drc_sim_c
Compile log at /opt/drc_sim/drc_sim_c/make.log
Installing drc_sim_c to /usr/local/bin
Compiled drc_sim_c
Installing DRC Sim Server GUI/CLI Utility
Found existing git directory /opt/drc_sim/drc
Stashed git changes
Updating git repo
Updated git repo
Installing setuptools
Attempting to remove previous installations
Using branch "master" for drc-sim install
Installing drc-sim
Downloading Python packages. This may take a while.
running install
running bdist_egg
running egg_info
writing requirements to drcsim.egg-info/requires.txt
writing top-level names to drcsim.egg-info/top_level.txt
writing dependency_links to drcsim.egg-info/dependency_links.txt
writing drcsim.egg-info/PKG-INFO
reading manifest file 'drcsim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'drcsim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/src
creating build/bdist.linux-x86_64/egg/src/__pycache__
copying build/lib/src/__pycache__/__init__.cpython-35.pyc -> build/bdist.linux-x86_64/egg/src/__pycache__
creating build/bdist.linux-x86_64/egg/src/server
creating build/bdist.linux-x86_64/egg/src/server/util
creating build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/logging/logger.py -> build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/logging/logger_wpa.py -> build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/logging/logger_cli.py -> build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/logging/logger_backend.py -> build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/logging/logger_gui.py -> build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/logging/__init__.py -> build/bdist.linux-x86_64/egg/src/server/util/logging
copying build/lib/src/server/util/os_util.py -> build/bdist.linux-x86_64/egg/src/server/util
copying build/lib/src/server/util/wpa_supplicant.py -> build/bdist.linux-x86_64/egg/src/server/util
copying build/lib/src/server/util/drc_sim_c.py -> build/bdist.linux-x86_64/egg/src/server/util
copying build/lib/src/server/util/interface_util.py -> build/bdist.linux-x86_64/egg/src/server/util
copying build/lib/src/server/util/status_sending_thread.py -> build/bdist.linux-x86_64/egg/src/server/util
copying build/lib/src/server/util/process_util.py -> build/bdist.linux-x86_64/egg/src/server/util
copying build/lib/src/server/util/__init__.py -> build/bdist.linux-x86_64/egg/src/server/util
creating build/bdist.linux-x86_64/egg/src/server/__pycache__
copying build/lib/src/server/__pycache__/__init__.cpython-35.pyc -> build/bdist.linux-x86_64/egg/src/server/__pycache__
creating build/bdist.linux-x86_64/egg/src/server/ui
creating build/bdist.linux-x86_64/egg/src/server/ui/cli
copying build/lib/src/server/ui/cli/cli_main.py -> build/bdist.linux-x86_64/egg/src/server/ui/cli
copying build/lib/src/server/ui/cli/__init__.py -> build/bdist.linux-x86_64/egg/src/server/ui/cli
creating build/bdist.linux-x86_64/egg/src/server/ui/gui
copying build/lib/src/server/ui/gui/gui_main.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui
creating build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/frame/frame_log.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/frame/frame_get_key.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/frame/frame_about.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/frame/frame_run_server.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/frame/frame_tab.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/frame/__init__.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui/frame
copying build/lib/src/server/ui/gui/__init__.py -> build/bdist.linux-x86_64/egg/src/server/ui/gui
copying build/lib/src/server/ui/__init__.py -> build/bdist.linux-x86_64/egg/src/server/ui
creating build/bdist.linux-x86_64/egg/src/server/data
copying build/lib/src/server/data/args.py -> build/bdist.linux-x86_64/egg/src/server/data
creating build/bdist.linux-x86_64/egg/src/server/data/__pycache__
copying build/lib/src/server/data/__pycache__/constants.cpython-35.pyc -> build/bdist.linux-x86_64/egg/src/server/data/__pycache__
copying build/lib/src/server/data/__pycache__/__init__.cpython-35.pyc -> build/bdist.linux-x86_64/egg/src/server/data/__pycache__
copying build/lib/src/server/data/constants.py -> build/bdist.linux-x86_64/egg/src/server/data
copying build/lib/src/server/data/resource.py -> build/bdist.linux-x86_64/egg/src/server/data
creating build/bdist.linux-x86_64/egg/src/server/data/struct
copying build/lib/src/server/data/struct/command.py -> build/bdist.linux-x86_64/egg/src/server/data/struct
copying build/lib/src/server/data/struct/input.py -> build/bdist.linux-x86_64/egg/src/server/data/struct
copying build/lib/src/server/data/struct/__init__.py -> build/bdist.linux-x86_64/egg/src/server/data/struct
copying build/lib/src/server/data/config.py -> build/bdist.linux-x86_64/egg/src/server/data
copying build/lib/src/server/data/config_general.py -> build/bdist.linux-x86_64/egg/src/server/data
copying build/lib/src/server/data/__init__.py -> build/bdist.linux-x86_64/egg/src/server/data
copying build/lib/src/server/__init__.py -> build/bdist.linux-x86_64/egg/src/server
copying build/lib/src/__init__.py -> build/bdist.linux-x86_64/egg/src
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/logging/logger.py to logger.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/logging/logger_wpa.py to logger_wpa.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/logging/logger_cli.py to logger_cli.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/logging/logger_backend.py to logger_backend.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/logging/logger_gui.py to logger_gui.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/logging/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/os_util.py to os_util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/wpa_supplicant.py to wpa_supplicant.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/drc_sim_c.py to drc_sim_c.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/interface_util.py to interface_util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/status_sending_thread.py to status_sending_thread.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/process_util.py to process_util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/util/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/cli/cli_main.py to cli_main.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/cli/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/gui_main.py to gui_main.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/frame/frame_log.py to frame_log.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/frame/frame_get_key.py to frame_get_key.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/frame/frame_about.py to frame_about.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/frame/frame_run_server.py to frame_run_server.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/frame/frame_tab.py to frame_tab.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/frame/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/gui/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/ui/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/args.py to args.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/resource.py to resource.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/struct/command.py to command.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/struct/input.py to input.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/struct/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/config.py to config.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/server/data/config_general.py to config_general.cpython-35.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/resources
creating build/bdist.linux-x86_64/egg/resources/config
copying resources/config/get_psk.conf -> build/bdist.linux-x86_64/egg/resources/config
creating build/bdist.linux-x86_64/egg/resources/image
copying resources/image/clover.gif -> build/bdist.linux-x86_64/egg/resources/image
copying resources/image/diamond.gif -> build/bdist.linux-x86_64/egg/resources/image
copying resources/image/heart.gif -> build/bdist.linux-x86_64/egg/resources/image
copying resources/image/spade.gif -> build/bdist.linux-x86_64/egg/resources/image
copying resources/image/icon.gif -> build/bdist.linux-x86_64/egg/resources/image
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.5/drc-sim-backend -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/drc-sim-backend to 755
copying drcsim.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying drcsim.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
src.server.data.__pycache__.resource.cpython-35: module references __file__
creating 'dist/drcsim-2.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing drcsim-2.0-py3.5.egg
creating /usr/local/lib/python3.5/dist-packages/drcsim-2.0-py3.5.egg
Extracting drcsim-2.0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding drcsim 2.0 to easy-install.pth file
Installing drc-sim-backend script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/drcsim-2.0-py3.5.egg
Processing dependencies for drcsim==2.0
Searching for netifaces>=0.10.5
Reading https://pypi.python.org/simple/netifaces/
Downloading https://pypi.python.org/packages/72/01/ba076082628901bca750bf53b322a8ff10c1d757dc29196a8e6082711c9d/netifaces-0.10.6.tar.gz#md5=1d424cb5ef52907c5ab913011122a98b
Best match: netifaces 0.10.6
Processing netifaces-0.10.6.tar.gz
Writing /tmp/easy_install-vp2516ld/netifaces-0.10.6/setup.cfg
Running netifaces-0.10.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vp2516ld/netifaces-0.10.6/egg-dist-tmp-lqcev1y5
checking for getifaddrs...found. 
checking for getnameinfo...found. 
checking for IPv6 socket IOCTLs...not found. 
checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h. 
checking whether struct sockaddr has a length field...no. 
checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ash ec ll atmpvc atmsvc dn irda llc. 
checking for routing socket support...no. 
checking for sysctl(CTL_NET...) support...no. 
checking for netlink support...netifaces.c:1:20: fatal error: Python.h: No such file or directory
compilation terminated.
yes. 
will use netlink to read routing table
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Failed to install drc-sim

**Comment by opencma** [comment]
The install script is missing a dependency. Installing "python3-dev" manually should fix the compile error.
