### ISSUE TITLE
python pip error help me plz

### ISSUE THREAD

**Issue by Terminatorali** [rolandoislas/drc-sim#56]
ubuntu@ubuntu:~$ curl -s https://raw.githubusercontent.com/rolandoislas/drc-sim/develop/install.sh | sudo bash -s develop
Drc-sim installer (script version 1.2)
	https://github.com/rolandoislas/drc-sim
Command apt-get found.
Installing dependencies.
python3 [INSTALLED]
python3-pip [INSTALLING]
python3-pip [FAILED]

**Comment by Terminatorali** [comment]
i need urgent help im new with this please help me

**Comment by opencma** [comment]
Run apt update.
