### ISSUE TITLE
(idk where else to ask this)can drc-sim run with cemu emulator?

### ISSUE THREAD

**Issue by SophiaH67** [rolandoislas/drc-sim#57]
can drc-sim run with cemu emulator?

**Comment by opencma** [comment]
DRC Sim only supports pairing with physical Wii U hardware.

**Comment by CreeperMario** [comment]
I haven't used Cemu in a long time (don't have a computer that seems to be compatible with it), but from what I remember, the GamePad screen is displayed instead of the TV screen when the Tab key is pressed (or something like that, maybe it was left Shift?).
