### ISSUE TITLE
Connection won't stay

### ISSUE THREAD

**Issue by samsungrocks10** [rolandoislas/drc-sim#6]
I run drc-sim.py, then drc-sim-helper and run the server, which connects drc-sim to my wii u, but the connection won't stay for more than 10-20 sec till it gives(drc-sim.py) me this error:

```
OverflowError: size does not fit in an int
Traceback (most recent call last):
  File "drc-sim.py", line 553, in <module>
    for event in pygame.event.get():
OverflowError

```
Or

```
OverflowError: size does not fit in an int
Traceback (most recent call last):
  File "drc-sim.py", line 556, in <module>
    elif event.type == pygame.VIDEORESIZE:
OverflowError
```

The Traceback changes sometimes

Before that error the audio goes weird and gives this a bunch of times 
"`ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred`"

**Comment by rolandoislas** [comment]
Version 1 is old and does not support the client/server functionality. The script `drc-sim-frontend.py` is the updated client.
