### ISSUE TITLE
(idk where else to ask this) can i use a 1.7Ghz CPU to run drc-sim?

### ISSUE THREAD

**Issue by milo1924** [rolandoislas/drc-sim#61]

**Comment by milo1924** [comment]
CPU : intel core i3 1.7Ghz (4 cores)
is this enough? or do i really need a 2.5GHz CPU?

**Comment by opencma** [comment]
You can try it, but expect poor performance if it does work.

**Comment by milo1924** [comment]
Quick update: it does work, using a panda N600 i get 90% of the speed (which means that the video has a little bit of delay). So yeah, for those that have a underpowered cpu give it a try, maybe it would work better than you expected.
