### ISSUE TITLE
Could not set interface 

### ISSUE THREAD

**Issue by somokol** [rolandoislas/drc-sim#64]
So I'm having issues trying get DRCSIM running.

My rig: Win10, VMware (latest), tried VirtualBox too, Panda Pau07 WiFI adapter (the one recommended), DualBand Router.

I've tried getting DRCSIM running in Debian 9, Ubuntu 18, and Ubuntu 14 Builds. I've been able to successfully pair, and sometimes get the server running, and run the client. But if I do get everything working, once I reboot the VM, I can never reconnect.

Is there a specific way a VM should be created and the script be installed. I typically just create a VM with a user account, and then run the install script. I'm wondering if there's issues with permissions on how the script is installing.

Contents of my wpa_supplicant_drc.log from my Debian 9 VM...

Successfully initialized wpa_supplicant
Could not set interface wlx9cefd5ff7bb4 flags (UP): No such file or directory
nl80211: Could not set interface 'wlx9cefd5ff7bb4' UP
nl80211: deinit ifname=wlx9cefd5ff7bb4 disabled_11b_rates=0
wlx9cefd5ff7bb4: Failed to initialize driver interface

I can't post the contents of drc_sim_c.log since it never wants to create the file on any VM, in the root folder or the drc folder it creates in Home. And if I create it manually, nothing gets written to it.

At this point, I'm not sure if the issue lies with VMware, Win10, or my WiFI adapter.

Any help or tips is appreciated, and thank you for all your time and effort making this project.

**Comment by Veemyu** [comment]
You just need to Resync with the Wii U once the VM is rebooted.
Just press the Red button on your Wii U Twice and resync in DRC SIM

**Comment by somokol** [comment]
> 
> 
> You just need to Resync with the Wii U once the VM is rebooted.
> Just press the Red button on your Wii U Twice and resync in DRC SIM

Thanks for the reply. Re-syncying doesn't resolve the issue. The server simply does not connect, and I'm unsure of what's blocking the connection.  I can get it to pair, just not start the server.

If you don't mind sharing, what is your setup, in terms of OS you connect on? Do you use a VM, and if so is it Virtualbox or VMware? Also your network adapter model.

Thanks for any advice.

**Comment by somokol** [comment]
You can close this.

I decided to just format a drive and install Ubuntu Mate 18 on the drive, rather than use a VM.

DRCSIM worked perfectly on the HDD install of Ubuntu Mate 18. 

Not sure what the issue was, but a virtual machine on Windows 10 did not work for me at all.
