### ISSUE TITLE
Failed to execute command WPA_Supplicant_drc -p

### ISSUE THREAD

**Issue by tanner02** [rolandoislas/drc-sim#79]
`drcsim Failed to execute command “['wpa_cli_drc' ,   '-p' ,   '/var/run/wpa_supplicant_drc', 'status']” and got output “Failed to connect to non-global ctrl-ifname:  (nil)   error: Success”
drcsim Failed to execute command “['wpa_cli_drc' ,   '-p' ,   '/var/run/wpa_supplicant_drc', 'scan-results']” and got output “Failed to connect to non-global ctrl-ifname:  (nil)   error: Success`

Host: Linux Mint 20 (5.9.0)

**Comment by themacintoshnerd** [comment]
how'd you fix this?

**Comment by tanner02** [comment]
@themacintoshnerd Sorry I barely remember anything about it anymore since it's been 2 years (and I didn't take any notes). But I **think** it happened when your network interface doesn't use the wpa_supplicant interface. Run `sudo systemctl stop NetworkManager` and `sudo systemctl disable NetworkManager` and then try running drc-sim again after exiting it. Hope this helps!
